### ISSUE TITLE
No recommmendation for warfarin in database but present on CPIC website

### ISSUE THREAD

**Issue by monigenomi** [cpicpgx/cpic-data#14]
On the CPIC website for drug warfarin there is info: "Because this guideline’s recommendations are based on genotype and not phenotype, the diplotype-phenotype tables were not created for these genes.": https://cpicpgx.org/guidelines/guideline-for-warfarin-and-cyp2c9-and-vkorc1/

This is underdestandable, but the database also lacks genotype recommendations for this drug. Is that known problem? Is it planned to include recommendations for warfarin (or more generally genome-based recommendations) in CPIC database?

Thank you for this awesome initiative!

**Comment by whaleyr** [comment]
Entries in the `recommendation` table only apply to guidelines that can go through the diplotype-to-phenotype process. The warfarin guideline cannot follow this method since it takes more information than just genotypes to make a recommendation. This is a known situation and there are no current plans to change it.

We added a note to the `guideline` object for Warfarin: https://api.cpicpgx.org/v1/guideline?name=like.*Warfarin*

You will see a `notesonusage` property that was placed there to address this situation. Also, please read the original guideline publications for a thorough explanation of how the guideline should be used.

**Comment by monigenomi** [comment]
Indeed :) I just thought it would be more reasonable to put this note as a record in `recommendation` table with `drugrecommendation` the same as `noteonusage`, and `phenotypes` fields set to `{"CYP2C9": "", "VKORC1": ""}` (meaning that this recommendation is not simple phenotype-based recommendation, but rather depends on genotypes for these genes being available). Please note that I haven't listed `CYP4F2` because it's an optional requirement for figuring out a proper dose according to [the diagram](http://files.cpicpgx.org/images/warfarin/warfarin_recommendation_diagram.png)).

I think it's better approach because single guideline can have multiple non-phenotype recommendations, and current structure doesn't reflect that fact. Given current solution you also can't know which genotypes are required and which are optional for given recommendation.
