### ISSUE TITLE
Guideline for Warfarin

### ISSUE THREAD

**Issue by aviguille** [cpicpgx/cpic-data#29]
Hi,

the guideline for Warfarin does not appear to be inside the database. Is there any plan to include it?

Also, in the paper ("Clinical Pharmacogenetics Implementation Consortium (CPIC) Guideline for Pharmacogenetics-Guided Warfarin Dosing: 2017 Update"), below Figure 2 says "...(e) Consider an alternative agent in individuals with genotypes associated with CYP2C9 poor metabolism (e.g., CYP2C9*3/*3, *2/*3, *3/*3)..." The diplotype *3/*3 appears twice. Is that an errata? Should it be *2/*2?

Thanks

**Comment by aviguille** [comment]
I answer to myself to part of the question. *2/*2 cannot be because that corresponds to an Intermediate Metabolizer

**Comment by whaleyr** [comment]
> the guideline for Warfarin does not appear to be inside the database. Is there any plan to include it?

The guideline for wafarin is in the database. It is in the `guideline` table: https://api.cpicpgx.org/v1/guideline?id=eq.100425

Note the `notesonusage` property of the response.

You may be noticing that it's not in the `recommendation` table which is because you need to read the guideline and follow [the recommendation algorithm diagram](https://files.cpicpgx.org/images/warfarin/warfarin_recommendation_diagram.png)
