### ISSUE TITLE
Lookup key {"UGT1A1":{"*27":1,"*80+*28":1}} returns empty Json and {"UGT1A1":{"*27":1,"*28":1}} returns "Poor Metabolizer"

### ISSUE THREAD

**Issue by davidyuyuan** [cpicpgx/cpic-data#38]
According to [UGT1A1 Diplotype-Phenotype Table](https://files.cpicpgx.org/data/report/current/diplotype_phenotype/UGT1A1_Diplotype_Phenotype_Table.xlsx), *27/*80+*28 is a poor metabolizer. However the following query with the lookup key {"UGT1A1":{"*27":1,"*80+*28":1}} returns an empty Json:
https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={%22UGT1A1%22:{%22*27%22:1,%22*80+*28%22:1}}&drugname=in.(atazanavir,belinostat,dolutegravir,irinotecan,nilotinib,pazopanib,raltegravir)&order=drugname

If we use the lookup key of {"UGT1A1":{"*27":1,"*28":1}}, we get "Poor Metabolizer" correctly as shown in the spreadsheet:
https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={%22UGT1A1%22:%20{%22*27%22:%201,%20%22*28%22:%201}}&drugname=in.(atazanavir,belinostat,dolutegravir,irinotecan,nilotinib,pazopanib,raltegravir)&order=drugname

We also tried {"UGT1A1":{"*27":1,"*80":1,"*28":1}} as the lookup key, we got "Indeterminate" back, which is still different from what's in the spreadsheet:
https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={%22UGT1A1%22:{%22*27%22:1,%22*80%22:1,%22*28%22:1}}&drugname=in.(atazanavir,belinostat,dolutegravir,irinotecan,nilotinib,pazopanib,raltegravir)&order=drugname

Can you please advise what the correct  lookup key should be for *27/*80+*28?

**Comment by whaleyr** [comment]
Looking into it. It seems like PostgREST may have a problem processing the `+` as part of a JSON object key. I'm looking for a solution.

**Comment by whaleyr** [comment]
Looks like you need to "percent-encode" the `+` character in the allele name so your first request would be:
`https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup=%7B%22UGT1A1%22%3A%20%7B%22*80%2b*28%22%3A%202%7D%7D`

I just curld that URL and it worked as expected.

**Comment by davidyuyuan** [comment]
Thank you for the analysis. Your comment helped me to dig a bit further. The spec: [rfc 2396](https://www.ietf.org/rfc/rfc2396.txt) defines these as reserved.
  reserved    = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" | "$" | ","
However, "+" is used as part of the lookup key.
It is only the "+" needs to be percent encoded. The URL with the minimal URL encoding is: https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={"UGT1A1": {"*80%2b*28": 2}}

**Comment by whaleyr** [comment]
It really depends on your environment, string encoding can be tricky. Some tools will auto-encode for you.

Like take the following URL that you used as an example (but got mangled by the markdown processor because you forgot to escape the `*` characters):
```
https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={"UGT1A1":{"*80%2b*28":2}}
```

That works fine in a desktop web browser because it doesn't actually use that exact URL, it translates it to the following:

```
https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={%22UGT1A1%22:{%22*80%2b*28%22:2}}
```

You can see this if you open the dev tools and inspect the network requests. Also, if you take that first URL and try to use it in a curl command like:

```shell
curl 'https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={"UGT1A1":{"*80%2b*28":2}}'
```

It will fail with the following:

```
curl: (3) nested brace in URL position 80:
https://api.cpicpgx.org/v1/rpc/recommendation_lookup?diplotypelookup={"UGT1A1":{"*80%2b*28":2}}
```

Because in zsh it tries to interpret the curly brace `{` as shell syntax. So, really, it's a case-by-case basis for what tool you're using to construct the URL and make the HTTP request and what rules of character encoding you need to abide by.

**Comment by davidyuyuan** [comment]
Thank you, Ryan, for the further clarification.


Kind regards,


David Yu Yuan
***@***.***
